// Mocks generated by Mockito 5.4.4 from annotations
// in notely/test/features/notes/data/repositories/notes_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:notely/core/network/network_info.dart' as _i6;
import 'package:notely/features/notes/data/datasources/notes_local_datasource.dart'
    as _i5;
import 'package:notely/features/notes/data/datasources/notes_remote_datasource.dart'
    as _i3;
import 'package:notely/features/notes/data/models/note_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeNoteModel_0 extends _i1.SmartFake implements _i2.NoteModel {
  _FakeNoteModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [NotesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesRemoteDataSource extends _i1.Mock
    implements _i3.NotesRemoteDataSource {
  MockNotesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.NoteModel>> getNotes() => (super.noSuchMethod(
        Invocation.method(
          #getNotes,
          [],
        ),
        returnValue: _i4.Future<List<_i2.NoteModel>>.value(<_i2.NoteModel>[]),
      ) as _i4.Future<List<_i2.NoteModel>>);

  @override
  _i4.Future<_i2.NoteModel> getNoteById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getNoteById,
          [id],
        ),
        returnValue: _i4.Future<_i2.NoteModel>.value(_FakeNoteModel_0(
          this,
          Invocation.method(
            #getNoteById,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.NoteModel>);

  @override
  _i4.Future<_i2.NoteModel> createNote({
    required String? title,
    required String? content,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNote,
          [],
          {
            #title: title,
            #content: content,
          },
        ),
        returnValue: _i4.Future<_i2.NoteModel>.value(_FakeNoteModel_0(
          this,
          Invocation.method(
            #createNote,
            [],
            {
              #title: title,
              #content: content,
            },
          ),
        )),
      ) as _i4.Future<_i2.NoteModel>);

  @override
  _i4.Future<_i2.NoteModel> updateNote(_i2.NoteModel? note) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateNote,
          [note],
        ),
        returnValue: _i4.Future<_i2.NoteModel>.value(_FakeNoteModel_0(
          this,
          Invocation.method(
            #updateNote,
            [note],
          ),
        )),
      ) as _i4.Future<_i2.NoteModel>);

  @override
  _i4.Future<void> deleteNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NotesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotesLocalDataSource extends _i1.Mock
    implements _i5.NotesLocalDataSource {
  MockNotesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.NoteModel> getCachedNotes() => (super.noSuchMethod(
        Invocation.method(
          #getCachedNotes,
          [],
        ),
        returnValue: <_i2.NoteModel>[],
      ) as List<_i2.NoteModel>);

  @override
  _i4.Future<void> cacheNotes(List<_i2.NoteModel>? notes) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheNotes,
          [notes],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cacheNote(_i2.NoteModel? note) => (super.noSuchMethod(
        Invocation.method(
          #cacheNote,
          [note],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteCachedNote(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteCachedNote,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
